### ISSUE TITLE
Question: comparison to other graph extractors for Java

### ISSUE THREAD

**Issue by bzz** [SERG-Delft/j2graph#9]
Hi, it would be interesting to understand better how is it comparable to other graph extractors for Java e.g. https://github.com/acr31/features-javac

Thanks!

**Comment by mauricioaniche** [comment]
There seems to be small differences on the generated graph! My tool here has lots of room for improvement (e.g., better data flow, more test cases to make sure everything works, etc)

But maybe more importantly is that this tool only requires source code whereas the other tool requires compiled code!

**Comment by bzz** [comment]
Thank you @mauricioaniche !
